# ===================================================================
# Spring Boot configuration for the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    file:
        name: log/application.log
    level:
        ROOT: ERROR
        sistemavendas.src.main.java.corp.ambiental.sistemavendas: DEBUG

spring:
    profiles:
        active: dev
        include:
            - swagger
            # Uncomment to activate TLS for the dev profile
            #- tls
    jackson:
        serialization:
            indent-output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
#        url: jdbc:sqlserver://brk-dev-opus.cbibhmphwidp.us-east-1.rds.amazonaws.com:31514;database=contas;schema=conta;SelectMethod=cursor
#        username: conta
#        password: qosieT5TbB4jSvJ9iUah
        url: jdbc:sqlserver://localhost:1433;database=pagtocartaocredito-dev;schema=conta;SelectMethod=cursor
        username: sistema
        password: 123

        hikari:
            poolName: Hikari
            auto-commit: false
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    flyway:
        locations: filesystem:src/main/resources/db/migration
        out-of-order: true
        enabled: true

    jpa:
        show-sql: false
        properties:
            hibernate.jdbc.time_zone: UTC

server:
    port: 8082

# ===================================================================
# Application specific properties
# ===================================================================
application:
    brk:
        auth:
            username: "sistema"
            password: "sistema"
